name: Deploy to EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to EC2 and Run Docker
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@<YOUR_EC2_PUBLIC_IP> "
          cd ~/app || mkdir ~/app && cd ~/app
          rm -rf *
        "
        scp -o StrictHostKeyChecking=no -r . ec2-user@<YOUR_EC2_PUBLIC_IP>:~/app

        ssh -o StrictHostKeyChecking=no ec2-user@<YOUR_EC2_PUBLIC_IP> "
          cd ~/app
          docker stop myapp || true
          docker rm myapp || true
          docker build -t myapp .
          docker run -d -p 3000:3000 --name myapp myapp
        "
